"""Patch engine - validates and applies AI-generated patches.

Guards:
- file paths must resolve inside the working copy (no traversal)
- only text files under the project root
- the `old` snippet must exist verbatim (exactly once) in the target file
- patches are applied to the *working copy* - the original is immutable
- every patch produces a unified diff + explanation stored with the patch
"""
from __future__ import annotations

import difflib
import re
from pathlib import Path
from typing import Any

from events import log
from services.scan_context import ScanContext

GENERATED_TEST_HEADER = (
    "# AI GENERATED REGRESSION TEST - generated by SentinelForge AI.\n"
    "# Validates that the original vulnerability no longer reproduces.\n"
)

ALLOWED_EXT = {".py", ".js", ".jsx", ".ts", ".tsx", ".go", ".rb", ".php", ".java", ".html", ".vue", ".svelte", ".css", ".json", ".yml", ".yaml", ".sh", ".toml", ".ini", ".conf", ".txt", ".sql", ".env", ".env.example"}


class PatchError(Exception):
    pass


def resolve_in(root: Path, rel: str) -> Path:
    if not rel or "\x00" in rel:
        raise PatchError("empty or invalid file path")
    candidate = (root / rel).resolve()
    if not candidate.is_relative_to(root.resolve()):
        raise PatchError(f"path escapes workspace: {rel}")
    return candidate


def validate_patch(patch: dict[str, Any], ctx: ScanContext) -> list[str]:
    """Validate structure + snippet existence. Returns list of errors."""
    errors: list[str] = []
    files = patch.get("files") or {}
    if not isinstance(files, dict) or not files:
        return ["patch contains no file changes"]
    for rel, change in files.items():
        if not isinstance(change, dict) or "old" not in change or "new" not in change:
            errors.append(f"{rel}: change must have old/new snippets")
            continue
        try:
            target = resolve_in(ctx.working, rel)
        except PatchError as exc:
            errors.append(str(exc))
            continue
        if target.suffix.lower() not in ALLOWED_EXT:
            errors.append(f"{rel}: file type not patchable")
            continue
        if not target.exists():
            errors.append(f"{rel}: file does not exist in working copy")
            continue
        old = change["old"]
        if not old or not old.strip():
            errors.append(f"{rel}: old snippet is empty")
            continue
        try:
            text = target.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            errors.append(f"{rel}: cannot read file ({exc})")
            continue
        count = text.count(old)
        if count == 0:
            errors.append(f"{rel}: old snippet not found verbatim (maybe whitespace differs)")
        elif count > 1:
            errors.append(f"{rel}: old snippet is ambiguous ({count} occurrences) - make it more specific")
    return errors


def apply_patch(patch: dict[str, Any], ctx: ScanContext) -> tuple[bool, list[dict[str, Any]], str]:
    """Apply a validated patch to the working copy. Returns (ok, changed_files, diff)."""
    files = patch.get("files") or {}
    changed: list[dict[str, Any]] = []
    diff_parts: list[str] = []
    for rel, change in files.items():
        target = resolve_in(ctx.working, rel)
        old = change["old"]
        new = change["new"]
        text = target.read_text(encoding="utf-8", errors="replace")
        # preserve exact replace (validated to occur exactly once)
        updated = text.replace(old, new, 1)
        target.write_text(updated, encoding="utf-8")
        diff = "\n".join(difflib.unified_diff(text.splitlines(), updated.splitlines(), fromfile=f"before/{rel}", tofile=f"after/{rel}", lineterm=""))
        diff_parts.append(diff)
        changed.append({"file": rel, "before": old, "after": new, "diff": diff})
        log(ctx.scan_id, f"Patched {rel} ({len(old)} → {len(new)} chars)")
    return True, changed, "\n".join(diff_parts)


def build_diff_text(before: str, after: str, rel: str) -> str:
    return "\n".join(difflib.unified_diff(before.splitlines(), after.splitlines(), fromfile=f"before/{rel}", tofile=f"after/{rel}", lineterm=""))


def write_regression_test(ctx: ScanContext, finding: dict[str, Any], content: str, preferred_file: str = "") -> str | None:
    """Write an AI-generated regression test into the working copy.

    Returns the relative path written, or None. The test is clearly labeled.
    """
    content = content.strip()
    if not content:
        return None
    content = GENERATED_TEST_HEADER + content
    detection = ctx.detection or {}
    frameworks = detection.get("frameworks") or []
    managers = detection.get("package_managers") or {}
    base = ""
    if "python" in detection.get("languages", {}) or any(f in frameworks for f in ("fastapi", "flask", "django")):
        base = "tests/generated" if (ctx.working / "tests").exists() else "test"
        ext = ".py"
    elif "javascript" in detection.get("languages", {}) or "typescript" in detection.get("languages", {}) or "npm" in managers:
        base = "tests/generated"
        ext = ".test.js"
        if "typescript" in detection.get("languages", {}):
            ext = ".test.ts"
    elif "go" in detection.get("languages", {}):
        base = ""
        ext = "_test.go"
    elif "java" in detection.get("languages", {}):
        base = "src/test/java/generated"
        ext = "Test.java"
    else:
        return None

    dir_path = ctx.working / base
    dir_path.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^a-z0-9]+", "_", (finding.get("category") or "finding").lower())[:40]
    fname = preferred_file or f"sf_regression_{slug}{ext}"
    if not fname.endswith(ext):
        fname += ext
    rel_path = dir_path / fname
    if rel_path.is_relative_to(ctx.working):
        rel_path.write_text(content, encoding="utf-8")
        log(ctx.scan_id, f"Generated regression test: {rel_path.relative_to(ctx.working)}")
        return str(rel_path.relative_to(ctx.working))
    return None
