"""Explicit scan state machine (see §30)."""

STATES = [
    "UPLOADED", "VALIDATING", "EXTRACTING", "ANALYZING", "BUILDING",
    "RUNNING", "DISCOVERING", "STATIC_ANALYSIS", "DEPENDENCY_ANALYSIS",
    "SECRET_ANALYSIS", "DYNAMIC_TESTING", "BROWSER_TESTING", "FUZZING",
    "BUG_HUNTING", "CORRELATING", "AI_ANALYSIS", "REPAIRING",
    "REBUILDING", "VERIFYING", "REPORTING", "COMPLETED", "FAILED",
    "CANCELLED",
]

TERMINAL = {"COMPLETED", "FAILED", "CANCELLED"}

TRANSITIONS: dict[str, list[str]] = {
    "UPLOADED": ["VALIDATING", "FAILED", "CANCELLED"],
    "VALIDATING": ["EXTRACTING", "FAILED", "CANCELLED"],
    "EXTRACTING": ["ANALYZING", "FAILED", "CANCELLED"],
    "ANALYZING": ["BUILDING", "FAILED", "CANCELLED"],
    "BUILDING": ["RUNNING", "FAILED", "CANCELLED"],
    "RUNNING": ["DISCOVERING", "FAILED", "CANCELLED"],
    "DISCOVERING": ["STATIC_ANALYSIS", "DEPENDENCY_ANALYSIS", "SECRET_ANALYSIS", "DYNAMIC_TESTING", "FAILED", "CANCELLED"],
    "STATIC_ANALYSIS": ["DEPENDENCY_ANALYSIS", "SECRET_ANALYSIS", "DYNAMIC_TESTING", "FAILED", "CANCELLED"],
    "DEPENDENCY_ANALYSIS": ["SECRET_ANALYSIS", "DYNAMIC_TESTING", "FAILED", "CANCELLED"],
    "SECRET_ANALYSIS": ["DYNAMIC_TESTING", "FAILED", "CANCELLED"],
    "DYNAMIC_TESTING": ["BROWSER_TESTING", "FUZZING", "BUG_HUNTING", "FAILED", "CANCELLED"],
    "BROWSER_TESTING": ["FUZZING", "BUG_HUNTING", "FAILED", "CANCELLED"],
    "FUZZING": ["BUG_HUNTING", "FAILED", "CANCELLED"],
    "BUG_HUNTING": ["CORRELATING", "FAILED", "CANCELLED"],
    "CORRELATING": ["AI_ANALYSIS", "FAILED", "CANCELLED"],
    "AI_ANALYSIS": ["REPAIRING", "VERIFYING", "REPORTING", "FAILED", "CANCELLED"],
    "REPAIRING": ["REBUILDING", "VERIFYING", "REPORTING", "FAILED", "CANCELLED"],
    "REBUILDING": ["VERIFYING", "REPORTING", "FAILED", "CANCELLED"],
    "VERIFYING": ["REPORTING", "FAILED", "CANCELLED"],
    "REPORTING": ["COMPLETED", "FAILED", "CANCELLED"],
}


class InvalidTransition(Exception):
    pass


def can_transition(current: str, target: str) -> bool:
    if current == target:
        return True
    return target in TRANSITIONS.get(current, [])
